source("utils.R")
source("likelihoods.R")
source("priors.R")
source('estimatorClass.R')
source('simulationClass.R')
source('generateMethod.R')
source('plotSimulationMethod.R')
source('estimationMethod.R')
source('estimationMaxmax.R')
source('estimationMleMap.R')
source('distributionClass.R')
source('computeDistributionsMethod.R')
source('plotDistributionMethod.R')

set.seed(1234)
## Simulate the observations, with generative model with compact orbits
simdelta <- simulation(in_n=100)
simdelta <- generate(simdelta)
simgauss<- simulation(in_n=100,in_eta=0.1)
simgauss <- generate(simgauss)

# ## Initialize the different estimators (0bjects)
# maxmaxperf <- estimator(method='maxmax with perfect registration')
# maxmaxusual <- estimator(method='maxmax usual')
# maxmaxreg <- estimator(method='maxmax with regularization')
# mledelta <- estimator(method='mle Delta')
# mlegauss <- estimator(method='mle Gaussian')
# mapdelta <- estimator(method='map Delta')
# mapgauss <- estimator(method='map Gaussian')
# 
# ## Run estimation
# cat(' ############ Simulation with Delta on orbits ############  \n')
# maxmaxperf <- estimation(maxmaxperf,simdelta)
# # print(maxmaxperf$coefficient)
# maxmaxusual <- estimation(maxmaxusual,simdelta)
# # print(maxmaxusual$coefficient)
# maxmaxreg <- estimation(maxmaxreg,simdelta)
# # print(maxmaxreg$coefficient)
# mledelta <- estimation(mledelta,simdelta)
# # print(mledelta$coefficient)
# mapdelta <- estimation(mapdelta,simdelta)
# # print(mapdelta$coefficient)
# cat(' ############ Simulation with Gaussian on orbits ############  \n')
# maxmaxperf <- estimation(maxmaxperf,simgauss)
# # print(maxmaxperf$coefficient)
# maxmaxusual <- estimation(maxmaxusual,simgauss)
# # print(maxmaxusual$coefficient)
# maxmaxreg <- estimation(maxmaxreg,simgauss)
# # print(maxmaxreg$coefficient)
# mlegauss <- estimation(mlegauss,simgauss)
# # print(mlegauss$coefficient)
# mapgauss <- estimation(mapgauss,simgauss)
# # print(mapgauss$coefficient)

# Evaluate the estimators
## Initialize the different estimators (0bjects)
mmperf_Distributions <- distributions(method='maxmax with perfect registration')
mmusual_Distributions <- distributions(method='maxmax usual')
mmreg_Distributions <- distributions(method='maxmax with regularization')
mledelta_Distributions <- distributions(method='mle Delta')
mlegauss_Distributions <- distributions(method='mle Gaussian')
mapdelta_Distributions <- distributions(method='map Delta')
mapgauss_Distributions <- distributions(method='map Gaussian')
Nexp = 200
# Compute the distributions for Delta simulation
mmperfdelta_Distributions <- computeDistributions(mmperf_Distributions,simdelta)
mmusualdelta_Distributions <- computeDistributions(mmusual_Distributions,simdelta)
mmregdelta_Distributions <- computeDistributions(mmreg_Distributions,simdelta)
mledelta_Distributions <- computeDistributions(mledelta_Distributions,simdelta)
mapdelta_Distributions <- computeDistributions(mapdelta_Distributions,simdelta)
## Compute the distributions for Gaussian simulation
mmperfgauss_Distributions <- computeDistributions(mmperf_Distributions,simgauss)
mmusualgauss_Distributions <- computeDistributions(mmusual_Distributions,simgauss)
mmreggauss_Distributions <- computeDistributions(mmreg_Distributions,simgauss)
mlegauss_Distributions <- computeDistributions(mlegauss_Distributions,simgauss)
mapgauss_Distributions <- computeDistributions(mapgauss_Distributions,simgauss)


## Save the results in files
# For delta
save(mmperfdelta_Distributions, file = 'mmperfdelta_Distributions')
save(mmusualdelta_Distributions, file = 'mmusualdelta_Distributions')
save(mmregdelta_Distributions, file = 'mmregdelta_Distributions')
save(mledelta_Distributions, file = 'mledelta_Distributions')
save(mapdelta_Distributions, file = 'mapdelta_Distributions')
# For Gaussian
save(mmperfgauss_Distributions, file = 'mmperfgauss_Distributions')
save(mmusualgauss_Distributions, file = 'mmusualgauss_Distributions')
save(mmreggauss_Distributions, file = 'mmreggauss_Distributions')
save(mlegauss_Distributions, file = 'mlegauss_Distributions')
save(mapgauss_Distributions, file = 'mapgauss_Distributions')

# 
# ## Plot the distributions of the template
# # For delta simulations
# par(mfrow=c(2,3))
# plot(simdelta)
# plot(mmperfdelta_Distributions,'y0')
# plot(mmusualdelta_Distributions,'y0')
# plot(mmregdelta_Distributions,'y0')
# plot(mledelta_Distributions,'y0')
# plot(mapdelta_Distributions,'y0')
# # For gaussian simulations
# par(mfrow=c(2,3))
# plot(simgauss)
# plot(mmperfgauss_Distributions,'y0')
# plot(mmusualgauss_Distributions,'y0')
# plot(mmreggauss_Distributions,'y0')
# plot(mlegauss_Distributions,'y0')
# #plot(mapgauss_Distributions,'y0')